apiVersion: v1
kind: Secret
metadata:
  name: auth-basic
type: Opaque
stringData:
  .htpasswd: |
    user1:$apr1$6od0hNN8$x7D7Lr21pB7O0Y2uInD0l.

#data:
#  username: dXNlcjE=
#  password: cGFzc3dvcmQx
#stringData:
#  username: user1
#  password: password1